# Site settings
title: Ata ul Mohsin
description: 'Agile project management, lazy, ailurophile.'
url: 'http://ataulmohsin.com'
baseurl: '/'
google_analytics: 'UA-70415595-1'

author:
  name: 'Ata ul Mohsin'
  twitter_username: ataulmohsin_
  linkedin_username: ataulmohsin
  github_username: ataulmohsin
  lastfm_username: mohcinshah

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
